// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkyV9lrkhIYSG7gW0_A_t4GMn52F8J-vE',
    appId: '1:1087957213781:web:66c56dad3f399dd944eadc',
    messagingSenderId: '1087957213781',
    projectId: 'apptik1',
    authDomain: 'apptik1.firebaseapp.com',
    storageBucket: 'apptik1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJhwudBpaUCviWLDhCxQ7KBx-xDxbXTA',
    appId: '1:1087957213781:android:a0aa83afadeb148b44eadc',
    messagingSenderId: '1087957213781',
    projectId: 'apptik1',
    storageBucket: 'apptik1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp5htH73FUiKpD3r4JtGmRRyz_Z58g_Bo',
    appId: '1:1087957213781:ios:282b5829b3330dee44eadc',
    messagingSenderId: '1087957213781',
    projectId: 'apptik1',
    storageBucket: 'apptik1.firebasestorage.app',
    iosBundleId: 'com.example.apptik1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp5htH73FUiKpD3r4JtGmRRyz_Z58g_Bo',
    appId: '1:1087957213781:ios:282b5829b3330dee44eadc',
    messagingSenderId: '1087957213781',
    projectId: 'apptik1',
    storageBucket: 'apptik1.firebasestorage.app',
    iosBundleId: 'com.example.apptik1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkyV9lrkhIYSG7gW0_A_t4GMn52F8J-vE',
    appId: '1:1087957213781:web:4cfbbe1fe8164aa844eadc',
    messagingSenderId: '1087957213781',
    projectId: 'apptik1',
    authDomain: 'apptik1.firebaseapp.com',
    storageBucket: 'apptik1.firebasestorage.app',
  );

}